abstract class OrderDetailsState{}
class InitialOrderDetailsState extends OrderDetailsState{}
class GetCurrentLocOrderDetailsSuccessState extends OrderDetailsState{}
class GetCurrentLocOrderDetailsLoadingState extends OrderDetailsState{}
class AddDriverMarkerState extends OrderDetailsState{}